apiVersion: apps/v1 # Change to "apps/v1beta1" for Kubernetes < 1.10.
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
spec:
  serviceName: {{ template "fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      role: {{ .Values.selector.role }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        role: {{ .Values.selector.role }}
      annotations:
        checksum/configMap: {{ toYaml .Values.configMap | sha256sum }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- range $envVar := .Values.env }}
        - name: {{ $envVar.name }}
          value: {{ $envVar.value }}
{{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        volumeMounts:
        - name: "mgob-storage"
          mountPath: "/storage"
        - name: "mgob-tmp"
          mountPath: "/tmp"
        - name: "mgob-tmp"
          mountPath: "/data"
{{- range $name, $value := .Values.configMap.data }}
        - mountPath: "/config/{{ $name }}"
          name: {{ $.Values.configMap.name }}
          subPath: {{ $name | quote }}
{{ end }}
{{- range $secret := .Values.secret }}
        - mountPath: "/secret/{{ $secret.name }}"
          name: {{ $secret.name }}
{{ end }}
      volumes:
      - name: {{ .Values.configMap.name }}
        configMap:
          name: {{ .Values.configMap.name }}
          items:
{{- range $name, $value := .Values.configMap.data }}
          - key: {{ $name }}
            path: {{ $name }}
{{ end }}
{{- range $secret := .Values.secret }}
      - name: {{ $secret.name }}
        secret:
          secretName: {{ $secret.name }}
{{ end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.storage.longTerm.name }}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storage.longTerm.storageClass }}
    spec:
      accessModes:
      - {{ .Values.storage.longTerm.accessMode }}
      resources:
        requests:
          storage: {{ .Values.storage.longTerm.size }}
  - metadata:
      name: {{ .Values.storage.tmp.name }}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storage.tmp.storageClass }}
    spec:
      accessModes:
      - {{ .Values.storage.tmp.accessMode }}
      resources:
        requests:
          storage: {{ .Values.storage.tmp.size }}
